export const LOAD_DORMAT_ACCOUNT_STARTED = "LOAD_DORMAT_ACCOUNT_STARTED";
export const LOAD_DORMAT_ACCOUNT_SUCCESS = "LOAD_DORMAT_ACCOUNT_SUCCESS";
export const LOAD_DORMAT_ACCOUNT_ERROR = "LOAD_DORMAT_ACCOUNT_ERROR";

export const SAVE_DORMAT_ACCOUNT_STARTED = "SAVE_DORMAT_ACCOUNT_STARTED";
export const SAVE_DORMAT_ACCOUNT_SUCCESS = "SAVE_DORMAT_ACCOUNT_SUCCESS";
export const SAVE_DORMAT_ACCOUNT_ERROR = "SAVE_DORMAT_ACCOUNT_ERROR";
