export const LOAD_CHEQUE_BOOK_CONFIGURATION_STARTED =
  "LOAD_CHEQUE_BOOK_CONFIGURATION_STARTED";
export const LOAD_CHEQUE_BOOK_CONFIGURATION_SUCCESS =
  "LOAD_CHEQUE_BOOK_CONFIGURATION_SUCCESS";
export const LOAD_CHEQUE_BOOK_CONFIGURATION_ERROR =
  "LOAD_CHEQUE_BOOK_CONFIGURATION_ERROR";

export const SAVE_CHEQUE_BOOK_CONFIGURATION_STARTED =
  "SAVE_CHEQUE_BOOK_CONFIGURATION_STARTED";
export const SAVE_CHEQUE_BOOK_CONFIGURATION_SUCCESS =
  "SAVE_CHEQUE_BOOK_CONFIGURATION_SUCCESS";
export const SAVE_CHEQUE_BOOK_CONFIGURATION_ERROR =
  "SAVE_CHEQUE_BOOK_CONFIGURATION_ERROR";
