export const LOAD_CREDIT_CARD_CONFIGURATION_STARTED =
  "LOAD_CREDIT_CARD_CONFIGURATION_STARTED";
export const LOAD_CREDIT_CARD_CONFIGURATION_SUCCESS =
  "LOAD_CREDIT_CARD_CONFIGURATION_SUCCESS";
export const LOAD_CREDIT_CARD_CONFIGURATION_ERROR =
  "LOAD_CREDIT_CARD_CONFIGURATION_ERROR";

export const SAVE_CREDIT_CARD_CONFIGURATION_STARTED =
  "SAVE_CREDIT_CARD_CONFIGURATION_STARTED";
export const SAVE_CREDIT_CARD_CONFIGURATION_SUCCESS =
  "SAVE_CREDIT_CARD_CONFIGURATION_SUCCESS";
export const SAVE_CREDIT_CARD_CONFIGURATION_ERROR =
  "SAVE_CREDIT_CARD_CONFIGURATION_ERROR";
