export const LOAD_BAR_DETAILS_STARTED = "LOAD_BAR_DETAILS_STARTED";
export const LOAD_BAR_DETAILS_SUCCESS = "LOAD_BAR_DETAILS_SUCCESS";
export const LOAD_BAR_DETAILS_ERROR = "LOAD_BAR_DETAILS_ERROR";

export const LOAD_DORMANT_BAR_DETAILS_STARTED =
  "LOAD_DORMANT_BAR_DETAILS_STARTED";
export const LOAD_DORMANT_BAR_DETAILS_SUCCESS =
  "LOAD_DORMANT_BAR_DETAILS_SUCCESS";
export const LOAD_DORMANT_BAR_DETAILS_ERROR = "LOAD_DORMANT_BAR_DETAILS_ERROR";

export const LOAD_CHEQUEBOOK_BAR_DETAILS_STARTED =
  "LOAD_CHEQUEBOOK_BAR_DETAILS_STARTED";
export const LOAD_CHEQUEBOOK_BAR_DETAILS_SUCCESS =
  "LOAD_CHEQUEBOOK_BAR_DETAILS_SUCCESS";
export const LOAD_CHEQUEBOOK_BAR_DETAILS_ERROR =
  "LOAD_CHEQUEBOOK_BAR_DETAILS_ERROR";

export const LOAD_CREDIT_CARD_BAR_DETAILS_STARTED =
  "LOAD_CREDIT_CARD_BAR_DETAILS_STARTED";
export const LOAD_CREDIT_CARD_BAR_DETAILS_SUCCESS =
  "LOAD_CREDIT_CARD_BAR_DETAILS_SUCCESS";
export const LOAD_CREDIT_CARD_BAR_DETAILS_ERROR =
  "LOAD_CREDIT_CARD_BAR_DETAILS_ERROR";
