export const LOAD_CREDIT_CARD_STARTED = "LOAD_CREDIT_CARD_STARTED";
export const LOAD_CREDIT_CARD_SUCCESS = "LOAD_CREDIT_CARD_SUCCESS";
export const LOAD_CREDIT_CARD_ERROR = "LOAD_CREDIT_CARD_ERROR";

export const SAVE_CREDIT_CARD_STARTED = "SAVE_CREDIT_CARD_STARTED";
export const SAVE_CREDIT_CARD_SUCCESS = "SAVE_CREDIT_CARD_SUCCESS";
export const SAVE_CREDIT_CARD_ERROR = "SAVE_CREDIT_CARD_ERROR";
