export const LOAD_OPEN_YOUR_ACCOUNT_STARTED = "LOAD_OPEN_YOUR_ACCOUNT_STARTED";
export const LOAD_OPEN_YOUR_ACCOUNT_SUCCESS = "LOAD_OPEN_YOUR_ACCOUNT_SUCCESS";
export const LOAD_OPEN_YOUR_ACCOUNT_ERROR = "LOAD_OPEN_YOUR_ACCOUNT_ERROR";

export const OPEN_YOUR_ACCOUNT_STARTED = "OPEN_YOUR_ACCOUNT_STARTED";
export const OPEN_YOUR_ACCOUNT_SUCCESS = "OPEN_YOUR_ACCOUNT_SUCCESS";
export const OPEN_YOUR_ACCOUNT_ERROR = "OPEN_YOUR_ACCOUNT_ERROR";
