export const LOAD_SELECT_MASTER_STARTED = "LOAD_SELECT_MASTER_STARTED";
export const LOAD_SELECT_MASTER_SUCCESS = "LOAD_SELECT_MASTER_SUCCESS";
export const LOAD_SELECT_MASTER_ERROR = "LOAD_SELECT_MASTER_ERROR";

export const SAVE_SELECT_MASTER_STARTED = "SAVE_SELECT_MASTER_STARTED";
export const SAVE_SELECT_MASTER_SUCCESS = "SAVE_SELECT_MASTER_SUCCESS";
export const SAVE_SELECT_MASTER_ERROR = "SAVE_SELECT_MASTER_ERROR";
