export const LOAD_CHEQUE_BOOK_STARTED = "LOAD_CHEQUE_BOOK_STARTED";
export const LOAD_CHEQUE_BOOK_SUCCESS = "LOAD_CHEQUE_BOOK_SUCCESS";
export const LOAD_CHEQUE_BOOK_ERROR = "LOAD_CHEQUE_BOOK_ERROR";

export const SAVE_CHEQUE_BOOK_STARTED = "SAVE_CHEQUE_BOOK_STARTED";
export const SAVE_CHEQUE_BOOK_SUCCESS = "SAVE_CHEQUE_BOOK_SUCCESS";
export const SAVE_CHEQUE_BOOK_ERROR = "SAVE_CHEQUE_BOOK_ERROR";
