export const LOAD_DORMAT_ACCOUNT_CONFIGURATION_STARTED =
  "LOAD_DORMAT_ACCOUNT_CONFIGURATION_STARTED";
export const LOAD_DORMAT_ACCOUNT_CONFIGURATION_SUCCESS =
  "LOAD_DORMAT_ACCOUNT_CONFIGURATION_SUCCESS";
export const LOAD_DORMAT_ACCOUNT_CONFIGURATION_ERROR =
  "LOAD_DORMAT_ACCOUNT_CONFIGURATION_ERROR";

export const SAVE_DORMAT_ACCOUNT_CONFIGURATION_STARTED =
  "SAVE_DORMAT_ACCOUNT_CONFIGURATION_STARTED";
export const SAVE_DORMAT_ACCOUNT_CONFIGURATION_SUCCESS =
  "SAVE_DORMAT_ACCOUNT_CONFIGURATION_SUCCESS";
export const SAVE_DORMAT_ACCOUNT_CONFIGURATION_ERROR =
  "SAVE_DORMAT_ACCOUNT_CONFIGURATION_ERROR";
